services:
  journal:
    command: null
    deploy:
      resources:
        limits:
          memory: 4GB
          cpus: "1.00"
        reservations:
          memory: 256MB
          cpus: "0.00"
      placement: {}
    entrypoint: null
    environment:
      DATABASE_URL: file:/data/journal.db
      JWT_SECRET: change-this-to-a-long-random-secret
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      NEXT_TELEMETRY_DISABLED: "1"
      NODE_ENV: production
    healthcheck:
      test:
        - CMD
        - wget
        - -qO-
        - http://localhost:3000/api/auth/me
      timeout: 5s
      interval: 30s
      retries: 3
      start_period: 20s
    image: ghcr.io/nmemmert/journal:main
    network_mode: bridge
    ports:
      - mode: ingress
        target: 3000
        published: "3333"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: db-data
        target: /data
        volume: {}
      - type: bind
        source: uploads
        target: /app/public/uploads
        volume: {}

volumes:
  db-data:
    name: compose-17a17415b875d195_db-data
    external: false
  uploads:
    name: compose-17a17415b875d195_uploads
    external: false

x-casaos:
  hostname: ""
  index: /
  is_uncontrolled: false
  main: journal
  port_map: "3333"
  scheme: http
  store_app_id: compose-17a17415b875d195
  title:
    custom: journal
